### ISSUE TITLE
ParseIDs should accept a list of ids

### ISSUE THREAD

**Issue by ssbb** [absinthe-graphql/absinthe_relay#59]
Example usage: 

```
arg :features, list_of(:id)

middleware Absinthe.Relay.Node.ParseIDs, features: :feature
```

Gives an error:

```
    ** (FunctionClauseError) no function clause matching in Base.decode64/2
        (elixir) lib/base.ex:309: Base.decode64([], [])
        lib/absinthe/relay/node.ex:161: Absinthe.Relay.Node.from_global_id/2
        lib/absinthe/relay/node/parse_ids.ex:119: anonymous fn/4 in Absinthe.Relay.Node.ParseIDs.parse/3
        (stdlib) lists.erl:1263: :lists.foldl/3
        lib/absinthe/relay/node/parse_ids.ex:117: Absinthe.Relay.Node.ParseIDs.parse/3
        lib/absinthe/relay/node/parse_ids.ex:104: Absinthe.Relay.Node.ParseIDs.call/2
        (absinthe) lib/absinthe/phase/document/execution/resolution.ex:191: Absinthe.Phase.Document.Execution.Resolution.reduce_resolution/1
        (absinthe) lib/absinthe/phase/document/execution/resolution.ex:161: Absinthe.Phase.Document.Execution.Resolution.do_resolve_field/4
        (absinthe) lib/absinthe/phase/document/execution/resolution.ex:147: Absinthe.Phase.Document.Execution.Resolution.do_resolve_fields/6
        (absinthe) lib/absinthe/phase/document/execution/resolution.ex:87: Absinthe.Phase.Document.Execution.Resolution.walk_result/5
        (absinthe) lib/absinthe/phase/document/execution/resolution.ex:57: Absinthe.Phase.Document.Execution.Resolution.perform_resolution/3
        (absinthe) lib/absinthe/phase/document/execution/resolution.ex:25: Absinthe.Phase.Document.Execution.Resolution.resolve_current/3
        (absinthe) lib/absinthe/pipeline.ex:247: Absinthe.Pipeline.run_phase/3
        (absinthe_plug) lib/absinthe/plug.ex:250: Absinthe.Plug.run_query/3
        (absinthe_plug) lib/absinthe/plug.ex:178: Absinthe.Plug.execute/2
        (absinthe_plug) lib/absinthe/plug.ex:139: Absinthe.Plug.call/2
        (phoenix) lib/phoenix/router/route.ex:161: Phoenix.Router.Route.forward/4
        (phoenix) lib/phoenix/router.ex:278: Phoenix.Router.__call__/1
        (exr) lib/exr/web/endpoint.ex:1: EXR.Web.Endpoint.plug_builder_call/2
        (exr) lib/plug/debugger.ex:123: EXR.Web.Endpoint."call (overridable 3)"/2
```

**Comment by bruce** [comment]
I'm currently working on a refactor branch that will support this feature.

**Comment by bruce** [comment]
This feature was added in v1.3.3.

**Comment by hickscorp** [comment]
Bumping as to me it seems that it still doesn't accept a list of IDs - only a list of children input args each of which may have an ID.

The documentation is very clear and helpful, but I'm not sure if it's lacking documentation for our use-case, or if it simply doesn't handle it at all.

Would it work with `field :children, non_null(list_of(non_null(:id)))` ?
Or would we have to wrap the children input field in another input object whose individual elements would have an ID field?
